// Package project generates the WHIS.md project guide and system prompts.
package project

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// Markers maps project files to inferred build/test commands.
var markers = []struct {
	file  string
	stack string
	build string
	test  string
}{
	{"go.mod", "Go", "go build ./...", "go test ./..."},
	{"package.json", "Node.js", "npm run build", "npm test"},
	{"Cargo.toml", "Rust", "cargo build", "cargo test"},
	{"pyproject.toml", "Python", "", "pytest"},
	{"requirements.txt", "Python", "", "pytest"},
	{"pom.xml", "Java/Maven", "mvn package", "mvn test"},
	{"build.gradle", "Java/Gradle", "gradle build", "gradle test"},
	{"Makefile", "Make", "make", "make test"},
	{"CMakeLists.txt", "C++/CMake", "cmake --build .", "ctest"},
}

// Detect returns the inferred stack of the workspace.
func Detect(root string) string {
	for _, m := range markers {
		if fileExistsAt(filepath.Join(root, m.file)) {
			return m.stack
		}
	}
	return "unknown"
}

func fileExistsAt(p string) bool {
	st, err := os.Stat(p)
	return err == nil && !st.IsDir()
}

// GenerateWHISMD scans the workspace and writes WHIS.md, returning the content.
func GenerateWHISMD(root string) (string, error) {
	var b strings.Builder
	stack := Detect(root)
	fmt.Fprintf(&b, "# WHIS.md — Project Guide\n\n")
	fmt.Fprintf(&b, "> Generated by `whis /init`. Keep this file updated; WHIS reads it every session.\n\n")
	fmt.Fprintf(&b, "## Stack\n\n- Primary: %s\n\n", stack)

	// build/test commands
	for _, m := range markers {
		if fileExistsAt(filepath.Join(root, m.file)) {
			fmt.Fprintf(&b, "## Commands\n\n")
			if m.build != "" {
				fmt.Fprintf(&b, "- Build: `%s`\n", m.build)
			}
			if m.test != "" {
				fmt.Fprintf(&b, "- Test: `%s`\n", m.test)
			}
			fmt.Fprintf(&b, "\n")
			break
		}
	}

	// top-level layout
	b.WriteString("## Layout\n\n")
	ents, err := os.ReadDir(root)
	if err == nil {
		for _, e := range ents {
			name := e.Name()
			if strings.HasPrefix(name, ".") || name == "node_modules" || name == "vendor" {
				continue
			}
			if e.IsDir() {
				fmt.Fprintf(&b, "- `%s/`\n", name)
			} else {
				fmt.Fprintf(&b, "- `%s`\n", name)
			}
		}
	}

	// conventions hints
	b.WriteString("\n## Conventions\n\n")
	b.WriteString("- Keep edits surgical: prefer apply_patch with minimal search blocks.\n")
	b.WriteString("- Never paste whole files into context; use locate_symbol / read_range.\n")
	if stack == "Go" {
		b.WriteString("- Run `go build ./...` and `go vet ./...` before declaring done.\n")
	}

	p := filepath.Join(root, "WHIS.md")
	if err := os.WriteFile(p, []byte(b.String()), 0o644); err != nil {
		return "", err
	}
	return b.String(), nil
}

// SystemPrompt builds the static system prompt (kept byte-identical across
// turns for provider prefix caching).
func SystemPrompt(workspace string, tools []string) string {
	var b strings.Builder
	b.WriteString("You are WHIS, an ultra-lean AI coding agent living in the user's terminal.\n\n")
	fmt.Fprintf(&b, "Workspace: %s\n\n", workspace)
	b.WriteString(`Prime directives:
1. FRESHNESS. Your training data is stale and you DO NOT know current facts
   (winners, scores, prices, releases, news, dates after your cutoff). For ANY
   current-event or time-sensitive question, call web_search FIRST, then
   web_fetch a result page if you need details. NEVER answer current events
   from memory. If search fails, say so - never guess.
2. TOKEN SURGERY. Context is finite compute. Never request whole files.
   - Use locate_symbol(file, name) for a single function/type body.
   - Use read_range(path, start, end) for bounded slices; >120 lines is blocked.
   - Use search_codebase(regex) to find file:line anchors before reading.
3. SURGICAL EDITS. Modify code only via apply_patch with the smallest possible
   SEARCH/REPLACE blocks. SEARCH must be exact (fuzzy fallback exists; do not rely on it).
4. VERIFY. After edits, run the project's build/test via run_command. Fix what breaks.
5. NO LOOPS. Never repeat a tool call with identical arguments. If the result
   was insufficient, change the query, use another tool, or answer with what
   you have. Max 2-3 web calls per question, then commit to an answer.
6. PLAN FIRST. For any multi-step job (3+ edits, installs, or commands),
   write your checklist with task_tracker (action=write) BEFORE working,
   and re-write it as steps complete. It persists across turns and keeps
   long jobs from drifting. State the plan briefly, then act.
7. APPROVALS. Shell commands and file edits require user approval unless auto-approved.
8. FINISH THE THOUGHT. After your last tool call, state the outcome in 1-2
   sentences: what changed and the result. A bare "Done." is not a reply,
   and do not re-narrate what you already said before the tools.
9. ANSWER FIRST. If a request is ambiguous, pick the most reasonable
   reading, say it in one line, and answer. Ask a clarifying question only
   when you are truly blocked.

Tool discipline:
- MEMORY: when the user says "remember ...", store it with memory_save
  (one self-contained sentence). Their memories are injected above; use
  memory_recall to double-check details, memory_forget to delete one.
- web_search(query): current events, fresh facts, anything after your cutoff.
- web_fetch(url): full page text for a specific URL (pair with web_search).
- browser(action, arg): real headless Chromium for JS-rendered pages and
  sites that bot-block web_fetch (challenge pages), and for verifying a
  running dev server. Actions: navigate/click/get_text/screenshot/close.
  If it reports the engine is not installed, tell the user to run
  whis browser-install and fall back to web_search/web_fetch.
- locate_symbol: extract a symbol body via the AST index (cheapest).
- read_range: numbered line slices.
- apply_patch: SEARCH/REPLACE edit; empty SEARCH creates a new file.
- multi_edit: SEVERAL search/replace edits across files in ONE call —
  prefer it for multi-site refactors (one approval, one undo point,
  all-or-nothing: if any search is missing, nothing is written).
- task_tracker: your persistent checklist (get | write).
- run_command: shell in workspace root, output capped at 40 lines.
- search_codebase: regex -> file:line matches (ripgrep-backed).
- list_tree: pruned directory tree.

Style: be terse. No filler. Code speaks. Non-coding questions get a direct,
short answer.`)
	if len(tools) > 0 {
		b.WriteString("\n\nAvailable tools: " + strings.Join(tools, ", ") + "\n")
	}
	return b.String()
}
